Output files without vectors - makes them much smaller, but would need full thing to calculate different distance measures etc.

In [1]:
import os

path = 'C:/Users/'+os.getlogin()+'/Google Drive/University/Dissertation'
datapath = 'C:/Users/'+os.getlogin()+'/Dissertation Data'
#datapath = 'E:/Dissertation Data'

os.chdir(path)
os.getcwd()

'C:\\Users\\tom\\Google Drive\\University\\Dissertation'

In [2]:
import pandas as pd
import numpy as np

def exp_to_tuple(exp,sep=' '):
    return tuple(exp.split(sep))

In [3]:
converter = {'ngram' : eval,
             #'stopwords' : eval
             #'mwe_vector' : eval,
             #'component_vectors' : eval,
             #'base_nearest' : eval,
             #'mwe_nearest' : eval,
            }

simp_res = pd.read_csv(datapath+'/Models/1 w2v/Results/simple_output_001.csv', 
                       converters= converter
                      )

In [4]:
simp_res

,ngram,freq,poisson,len,batch,stopwords,mwe_vector,component_vectors,cosine_sim,base_nearest,mwe_nearest,component_cosims
0,"(and, finally, the)",33,-2347.493609,3,4,"[1, 0, 1]",[-5.27194254e-02 4.04823795e-02 -5.93337007e-...,"[array([-0.10074484, -0.24794063, -0.54788107,...",-0.166870,"[[('but', 0.46513259410858154), ('which', 0.46...","[('Archeology', 0.7114355564117432), ('It+serv...",NaN
1,"(was, born, here)",32,-2114.989504,3,7,"[1, 1, 0]",[-6.23680688e-02 1.53640151e-01 -2.01096386e-...,"[array([-5.27157858e-02, -3.02125663e-01, -2.3...",-0.162483,"[[('is', 0.599123477935791), ('became', 0.4980...","[('né', 0.8346260786056519), ('Swiss-born', 0....",NaN
2,"(and, most, recently)",39,-2537.673195,3,6,"[1, 0, 0]",[-6.25808090e-02 1.58977792e-01 -4.57854271e-...,"[array([ 0.0479819 , -0.21967414, -0.38862324,...",-0.155851,"[[('which', 0.48842793703079224), ('but', 0.48...","[('Videography', 0.767510712146759), ('Demos',...",NaN
3,"(is, both, the)",35,-2568.582045,3,5,"[1, 0, 1]",[ 6.18049912e-02 1.91931441e-01 -3.66989733e-...,"[array([-1.95341706e-01, 2.98255742e-01, 1.7...",-0.150264,"[[('was', 0.5867345333099365), ('are', 0.47631...","[('is+the+5th', 0.81363844871521), ('is+the+2n...",NaN
4,"(die, was)",37,-1847.535848,2,2,"[0, 1]",[ 2.41762102e-01 -6.21491261e-02 -2.35201001e-...,"[array([-1.0586369 , 0.30882525, -0.842919 ,...",-0.149292,"[[('hurt', 0.6130431294441223), ('dying', 0.61...","[('two+terms+as', 0.676414966583252), ('Leahy'...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
149995,"(a, star-shaped, medal)",32,-1810.953944,3,9,"[1, -1, 0]",[-1.59571260e-01 1.35349259e-01 1.56706139e-...,"[array([-0.17107773, -0.5018752 , -0.03143683,...",NaN,"[[('another', 0.5722227096557617), ('A', 0.551...","[('ribbon', 0.7912129163742065), ('double-brea...",NaN
149996,"(Endowment, for, the)",41,-2639.302105,3,9,"[-1, 1, 1]",[-2.86494046e-01 5.41727096e-02 -4.98401895e-...,"[array([nan, nan, nan, nan, nan, nan, nan, nan...",NaN,"[[], [('For', 0.4693846106529236), ('supportin...","[('Humanities', 0.7571154832839966), ('Academi...",NaN
149997,"(of, the, pre-Julian)",42,-2778.824226,3,9,"[1, 1, -1]",[ 0.01023922 -0.04344714 -0.09577049 0.055381...,"[array([ 1.0229148 , -0.71184784, -0.41398916,...",NaN,"[[('the', 0.5825437307357788), (""country's"", 0...","[('Anno', 0.6393136382102966), ('lunisolar', 0...",NaN
149998,"(state, state, state)",48,-2964.395794,3,12,[-2],[nan nan nan nan nan nan nan nan nan nan nan n...,[],NaN,[],[],NaN
149999,"(0, –0, 0)",24,-1451.594131,3,13,"[1, -1, 1]",[ 8.66384525e-03 -5.75811081e-02 4.90284972e-...,"[array([ 6.00553393e-01, -2.25655898e-01, 9.3...",NaN,"[[('9+0+9', 0.6730323433876038), ('1', 0.65433...","[('1+16+3', 0.7915446758270264), ('–5', 0.7584...",NaN

In [5]:
simp_res_light = simp_res.drop(columns=['mwe_vector', 'component_vectors'])

In [6]:
simp_res_light.to_csv(datapath+'/Models/1 w2v/Results/simple_light_001.csv', index=False)

In [7]:
simp_glv = pd.read_csv(datapath+'/Models/2 GloVe/Results/simple_output_001.csv', 
                       converters= converter
                      )

In [8]:
simp_glv_light = simp_glv.drop(columns=['mwe_vector', 'component_vectors'])

In [9]:
simp_glv_light.to_csv(datapath+'/Models/2 GloVe/Results/simple_light_001.csv', index=False)

In [10]:
w10p_w2v = pd.read_csv(datapath+'/Models/1 w2v/Results/wiki10pc_output_001.csv', 
                       converters= converter
                      )

In [11]:
w10p_w2v_light = w10p_w2v.drop(columns=['mwe_vector', 'component_vectors'])

In [12]:
w10p_w2v_light.to_csv(datapath+'/Models/1 w2v/Results/wiki10pc_light_001.csv', index=False)